/**
 * N.E.O. the N.E.R.D. - Network Discovery + Control Feature
 * Mock Network Data
 *
 * This file contains simulated demo data for the network discovery module.
 * All data here is clearly fake and for demonstration purposes only.
 * Replace with real data from native/backend adapter when available.
 */

import type {
  NetworkStatus,
  DiscoveredDevice,
  RouterStatus,
  SecurityInsight,
  ScanHistoryEntry,
  NetworkSettings,
  NetworkTopologyGraph,
} from "./types";
import { createDemoTopologyGraph } from "./topology";

export const MOCK_NETWORK_STATUS: NetworkStatus = {
  networkName: "NEO_COMMAND_NET",
  gatewayIp: "192.168.1.1",
  localIp: "192.168.1.42",
  subnet: "255.255.255.0",
  connectionType: "Wi-Fi",
  scanState: "idle",
  lastScanAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  devicesFound: 8,
  onlineDevices: 7,
  unknownDevices: 1,
  flaggedDevices: 2,
};

export const MOCK_DEVICES: DiscoveredDevice[] = [
  {
    id: "device-001",
    name: "Home Gateway",
    hostname: "router.local",
    ipAddress: "192.168.1.1",
    macAddress: "AA:BB:CC:11:22:33",
    vendor: "NETGEAR",
    deviceType: "router",
    status: "online",
    trustLevel: "trusted",
    firstSeen: "2026-01-15T08:00:00Z",
    lastSeen: new Date().toISOString(),
    openPorts: [80, 443, 53],
    services: ["HTTP", "HTTPS", "DNS"],
    notes: "Primary network gateway - demo device",
    latencyMs: 1,
    discoverySources: ["gateway", "arp", "tcp-probe"],
    confidence: "high",
    dataLimited: false,
    lastScanSource: "tcp-probe",
  },
  {
    id: "device-002",
    name: "Android Phone",
    hostname: "neo-phone",
    ipAddress: "192.168.1.42",
    macAddress: "DD:EE:FF:44:55:66",
    vendor: "Samsung",
    deviceType: "phone",
    status: "online",
    trustLevel: "trusted",
    firstSeen: "2026-02-20T14:30:00Z",
    lastSeen: new Date().toISOString(),
    openPorts: [],
    services: [],
    notes: "N.E.O. command device - demo",
    signalStrength: -45,
    latencyMs: 5,
    discoverySources: ["arp"],
    confidence: "medium",
    dataLimited: false,
    lastScanSource: "arp",
  },
  {
    id: "device-003",
    name: "Gaming Laptop",
    hostname: "DESKTOP-NEO",
    ipAddress: "192.168.1.100",
    macAddress: "11:22:33:AA:BB:CC",
    vendor: "ASUS",
    deviceType: "computer",
    status: "online",
    trustLevel: "trusted",
    firstSeen: "2026-01-20T10:00:00Z",
    lastSeen: new Date().toISOString(),
    openPorts: [22, 3389],
    services: ["SSH", "RDP"],
    notes: "Primary workstation - demo device",
    latencyMs: 3,
    discoverySources: ["arp", "tcp-probe", "hostname"],
    confidence: "high",
    dataLimited: false,
    lastScanSource: "hostname",
  },
  {
    id: "device-004",
    name: "Smart TV",
    hostname: "livingroom-tv",
    ipAddress: "192.168.1.150",
    macAddress: "44:55:66:DD:EE:FF",
    vendor: "LG",
    deviceType: "tv",
    status: "online",
    trustLevel: "watch",
    firstSeen: "2026-03-01T16:00:00Z",
    lastSeen: new Date().toISOString(),
    openPorts: [8080, 9000],
    services: ["WebOS", "DLNA"],
    notes: "Smart TV - monitoring for unusual activity - demo",
    latencyMs: 8,
    discoverySources: ["arp", "tcp-probe"],
    confidence: "high",
    dataLimited: false,
    lastScanSource: "tcp-probe",
  },
  {
    id: "device-005",
    name: "Unknown IoT Device",
    hostname: "esp-device",
    ipAddress: "192.168.1.201",
    macAddress: "77:88:99:00:11:22",
    vendor: "Unknown",
    deviceType: "unknown",
    status: "online",
    trustLevel: "new",
    firstSeen: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastSeen: new Date().toISOString(),
    openPorts: [80],
    services: ["HTTP"],
    notes: "",
    signalStrength: -70,
    latencyMs: 15,
    discoverySources: ["arp", "tcp-probe"],
    confidence: "medium",
    dataLimited: false,
    lastScanSource: "tcp-probe",
  },
  {
    id: "device-006",
    name: "Wireless Printer",
    hostname: "hp-printer",
    ipAddress: "192.168.1.180",
    macAddress: "AA:00:BB:11:CC:22",
    vendor: "HP",
    deviceType: "printer",
    status: "offline",
    trustLevel: "trusted",
    firstSeen: "2026-02-01T09:00:00Z",
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    openPorts: [631, 9100],
    services: ["IPP", "JetDirect"],
    notes: "Office printer - currently powered off - demo",
    latencyMs: undefined,
    discoverySources: ["arp"],
    confidence: "low",
    dataLimited: true,
    lastScanSource: "arp",
  },
  {
    id: "device-007",
    name: "Game Console",
    hostname: "playstation",
    ipAddress: "192.168.1.120",
    macAddress: "33:44:55:66:77:88",
    vendor: "Sony",
    deviceType: "console",
    status: "online",
    trustLevel: "trusted",
    firstSeen: "2026-01-25T20:00:00Z",
    lastSeen: new Date().toISOString(),
    openPorts: [3478, 3479, 3480],
    services: ["PSN"],
    notes: "Gaming console - demo device",
    latencyMs: 4,
    discoverySources: ["arp", "tcp-probe"],
    confidence: "high",
    dataLimited: false,
    lastScanSource: "tcp-probe",
  },
  {
    id: "device-008",
    name: "Smart Plug",
    hostname: "smart-plug-01",
    ipAddress: "192.168.1.210",
    macAddress: "99:AA:BB:CC:DD:EE",
    vendor: "TP-Link",
    deviceType: "iot",
    status: "online",
    trustLevel: "watch",
    firstSeen: "2026-04-10T12:00:00Z",
    lastSeen: new Date().toISOString(),
    openPorts: [9999],
    services: ["Kasa"],
    notes: "Smart plug - IoT device on watch list - demo",
    signalStrength: -55,
    latencyMs: 10,
    discoverySources: ["arp", "tcp-probe"],
    confidence: "medium",
    dataLimited: false,
    lastScanSource: "tcp-probe",
  },
];

export const MOCK_ROUTER_STATUS: RouterStatus = {
  name: "Home Gateway",
  model: "NETGEAR Nighthawk R7000",
  gatewayIp: "192.168.1.1",
  firmwareVersion: "V1.0.11.126 (Demo)",
  connectionStatus: "connected",
  uptime: "15 days, 7 hours, 23 minutes",
  wanIp: "203.0.113.42",
  dnsServers: ["8.8.8.8", "8.8.4.4"],
  guestNetworkEnabled: false,
  qosEnabled: true,
  firewallEnabled: true,
  rebootAvailable: true,
  readOnlyMode: true,
};

export const MOCK_SECURITY_INSIGHTS: SecurityInsight[] = [
  {
    id: "insight-001",
    severity: "medium",
    title: "New Device Detected",
    description:
      "An unknown IoT device joined the network 30 minutes ago. Review and classify this device.",
    relatedDeviceId: "device-005",
    recommendedAction: "Review device details and set trust level",
  },
  {
    id: "insight-002",
    severity: "low",
    title: "Unknown Vendor",
    description:
      "Device at 192.168.1.201 has an unrecognized vendor. This may be a generic IoT device.",
    relatedDeviceId: "device-005",
    recommendedAction: "Identify device and update name",
  },
  {
    id: "insight-003",
    severity: "info",
    title: "Open Ports Detected",
    description:
      "Smart TV has open ports 8080 and 9000. This is normal for smart TV functionality.",
    relatedDeviceId: "device-004",
    recommendedAction: "No action required - informational only",
  },
  {
    id: "insight-004",
    severity: "low",
    title: "Device Offline",
    description:
      "Wireless Printer has been offline for over 24 hours. It may be powered off.",
    relatedDeviceId: "device-006",
    recommendedAction: "Check if device should be online",
  },
  {
    id: "insight-005",
    severity: "info",
    title: "Router Read-Only Mode",
    description:
      "Router control is in read-only mode. Control actions are simulated until backend is connected.",
    recommendedAction: "Connect native backend to enable real control",
  },
];

export const MOCK_SCAN_HISTORY: ScanHistoryEntry[] = [
  {
    id: "scan-001",
    startedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    finishedAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    devicesFound: 8,
    newDevices: 1,
    offlineDevices: 1,
    flaggedDevices: 2,
    durationMs: 45000,
    scanMode: "balanced",
  },
  {
    id: "scan-002",
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    finishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2 + 30000).toISOString(),
    devicesFound: 7,
    newDevices: 0,
    offlineDevices: 1,
    flaggedDevices: 1,
    durationMs: 30000,
    scanMode: "quick",
  },
  {
    id: "scan-003",
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    finishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 + 120000).toISOString(),
    devicesFound: 7,
    newDevices: 0,
    offlineDevices: 0,
    flaggedDevices: 1,
    durationMs: 120000,
    scanMode: "deep",
  },
];

export const DEFAULT_NETWORK_SETTINGS: NetworkSettings = {
  scanMode: "balanced",
  autoScanEnabled: false,
  autoScanIntervalMinutes: 30,
  notifyNewDevices: true,
  notifyOfflineDevices: false,
  safeMode: true,
  allowControlActions: false,
  demoMode: true,
};

export const MOCK_NETWORK_TOPOLOGY: NetworkTopologyGraph = createDemoTopologyGraph(MOCK_DEVICES);
