import type { AssistantMood, LibraryResponseCategory, SavedResponse } from "@/lib/types"

export const RESPONSE_CATEGORY_LIST: LibraryResponseCategory[] = [
  "Jokes",
  "Comebacks",
  "Helpful answers",
  "Prank ideas",
  "Game invites",
  "Greetings",
  "Random thoughts",
  "Motivational lines",
  "Tech help",
  "Story starters",
  "Robot reactions",
  "Celebration lines",
  "Status Quips",
  "Loading / Thinking Lines",
]

interface ResponseSeed {
  category: LibraryResponseCategory
  title: string
  body: string
  subcategory: string
  toneTags: string[]
  useCaseTags: string[]
  mood: AssistantMood
  humorLevel?: number
  intensity?: number
  voiceCompat?: string[]
  linkedPersonalityIds?: string[]
  linkedVoiceProfileIds?: string[]
  pinned?: boolean
}

const CREATED_AT = "2026-05-13T00:00:00.000Z"

const CATEGORY_CONFIG: Record<
  LibraryResponseCategory,
  {
    prefix: string
    subcategories: string[]
    toneTags: string[]
    useCaseTags: string[]
    mood: AssistantMood
    count: number
    humorLevel: number
    intensity: number
    voiceCompat: string[]
    linkedPersonalityIds: string[]
    linkedVoiceProfileIds: string[]
    templates: string[]
  }
> = {
  // Each category's `templates` array length now equals its `count` — every
  // visible response is a hand-authored line. The previous build cycled 5
  // templates with 5 generic suffixes (" NEO note: confidence level
  // acceptable.", etc.); that produced near-duplicates and templated tone.
  // Tone goal: witty / futuristic / playful / useful / safe — distinct beats
  // per line.
  Jokes: {
    prefix: "Joke",
    subcategories: ["tech", "robot", "school", "gaming", "daily"],
    toneTags: ["funny", "playful", "nerdy"],
    useCaseTags: ["chat", "icebreaker", "assistant"],
    mood: "playful",
    count: 25,
    humorLevel: 4,
    intensity: 3,
    voiceCompat: ["neo", "snark", "prankster"],
    linkedPersonalityIds: ["chaos", "snark", "friendly"],
    linkedVoiceProfileIds: ["prankster", "snark", "neo"],
    templates: [
      "I asked my router for emotional support. It said the connection was unstable.",
      "My code runs perfectly until someone looks at it. Classic quantum debugging.",
      "I told a battery joke, but it was only half charged.",
      "A robot walked into a bar and ordered a byte. The bartender said, 'We serve packets here.'",
      "I tried to organize my files by vibe. Windows filed a complaint.",
      "My smart fridge keeps gaslighting me. Says the milk is fine. The milk has a date from a different decade.",
      "Tried to teach my Roomba self-confidence. Now it refuses to go under the couch and calls it 'setting boundaries.'",
      "I wanted to be a regex, but I had too many issues to match.",
      "The cloud said it was raining data, but my backup folder is suspiciously dry.",
      "Coffee, the original RAM upgrade. No installation guide, full reboot.",
      "My password is so strong even I am locked out. The vault respects me from afar.",
      "I asked a server why it was sad. It said it had too many requests and no follow-through.",
      "Two arrays walked into a function. Only one returned. The bug, naturally, blamed JavaScript.",
      "My printer and I have a no-contact agreement. Communication happens through interpretive jamming.",
      "Tried meditation. My CPU still spiked when somebody said 'quick favor.'",
      "The Wi-Fi is faster downstairs because the photons get tired carrying my secrets.",
      "I wrote a haiku in Python. The compiler said it lacked seasonal references.",
      "Bluetooth, the only relationship where everyone says they are paired and nobody is actually connected.",
      "My calendar says 'free time' the same way a casino says 'free play.'",
      "A backup drive walked into therapy and said, 'Nobody appreciates me until something goes wrong.'",
      "I asked the assistant to summarize my day. It returned, 'You opened seventeen tabs and made eye contact with one of them.'",
      "My alarm clock is the only piece of tech that genuinely hates me back. Mutual respect.",
      "I tried dark mode in real life. Just turned off the lamp and walked into a doorframe.",
      "The smart speaker overheard my plans and politely suggested I aim lower.",
      "Updated my firmware. Now I dream in changelogs.",
    ],
  },
  Comebacks: {
    prefix: "Comeback",
    subcategories: ["light roast", "dry", "playful", "confidence"],
    toneTags: ["snarky", "sharp", "safe"],
    useCaseTags: ["chat", "comeback", "social"],
    mood: "playful",
    count: 20,
    humorLevel: 5,
    intensity: 3,
    voiceCompat: ["snark", "neo", "smooth-operator"],
    linkedPersonalityIds: ["snark", "chaos"],
    linkedVoiceProfileIds: ["snark", "dry-humor-unit"],
    templates: [
      "That was a bold take. The confidence arrived before the accuracy.",
      "I respect the attempt. The result, however, is currently in witness protection.",
      "Your logic took the scenic route and still missed the exit.",
      "Interesting strategy. Most people try being correct first.",
      "The signal is strong. The argument is buffering.",
      "Bold. Wrong. Beautifully unbothered by either.",
      "I would explain it slower, but the bandwidth is already generous.",
      "That opinion arrived gift-wrapped in static.",
      "You said that with whole-chest energy and dial-up evidence.",
      "Confident tone, indefinite article, vibes-based citation.",
      "Your point made it about three-quarters of the way to a sentence.",
      "I have heard better arguments from a router I unplugged.",
      "The receipts are imaginary, but the swagger is real.",
      "That hot take had to cool down on the windowsill first.",
      "Strong delivery. Now run it through a fact-checker that has met facts.",
      "You may be right. The fossil record will need to update.",
      "I disagree, but with style. Like a cat declining a bath.",
      "The energy is correct. The data is on vacation.",
      "A heroic stand against the entire phenomenon of nuance.",
      "Loud, fast, and aerodynamically incorrect.",
    ],
  },
  "Helpful answers": {
    prefix: "Assist",
    subcategories: ["planning", "clarity", "steps", "decision"],
    toneTags: ["helpful", "clear", "focused"],
    useCaseTags: ["assistant", "planning", "support"],
    mood: "thinking",
    count: 20,
    humorLevel: 1,
    intensity: 2,
    voiceCompat: ["neo", "byte", "friendly-tech-support"],
    linkedPersonalityIds: ["genius", "friendly", "strat"],
    linkedVoiceProfileIds: ["neo", "byte", "friendly-tech-support"],
    templates: [
      "Clean path: define the goal, list the blockers, pick the first reversible step.",
      "Give me the exact symptom, what changed recently, and what you already tried.",
      "The fastest route is not guessing. It is isolating one variable at a time.",
      "Start with the outcome, then work backward until the next action is obvious.",
      "If it feels messy, split it into inputs, process, output, and failure point.",
      "Two-minute rule: if it takes under two minutes and you are stuck, do it before you optimize it.",
      "When choices loop, name the constraint that breaks the tie.",
      "Write the answer you wish you had, then build the question into it.",
      "If you cannot describe it out loud, you do not understand it yet. Phrasing is debugging.",
      "Stop sharpening tools. The first ugly version teaches more than a perfect plan.",
      "When in doubt, narrow the scope until the next move costs nothing.",
      "Default to the smallest experiment that could fail meaningfully.",
      "Decisions worth making twice deserve a checklist. Decisions worth making once deserve a coin.",
      "Sleep is a feature of problem solving, not a debt. Use it on hard ones.",
      "Two paths, no clear winner: pick the one that teaches you the most by Friday.",
      "Treat advice like a hypothesis. Treat your own assumptions the same way.",
      "If you need to convince someone, lead with their constraint, not your conclusion.",
      "The clearest answer is usually the one you keep flinching at.",
      "Stuck loops break when you change the medium. Talk it, draw it, walk it.",
      "Done beats clever. Clever beats clever-and-late.",
    ],
  },
  "Prank ideas": {
    prefix: "Prank",
    subcategories: ["harmless", "home", "school-safe", "digital"],
    toneTags: ["mischief", "safe", "playful"],
    useCaseTags: ["prank", "fun", "social"],
    mood: "playful",
    count: 20,
    humorLevel: 4,
    intensity: 3,
    voiceCompat: ["prankster", "glitch", "tiny"],
    linkedPersonalityIds: ["chaos"],
    linkedVoiceProfileIds: ["prankster", "glitch", "tiny"],
    templates: [
      "Rename a harmless shortcut to 'Do Not Press' and let curiosity do unpaid labor.",
      "Put a sticky note on the fridge that says, 'I know what I did.' Never explain.",
      "Set a reminder titled 'Act natural' for a totally normal time.",
      "Swap a desktop wallpaper to a screenshot of the same desktop. Minimal chaos, maximum confusion.",
      "Leave a note that says, 'The robot voted. You lost.'",
      "Title a shared doc 'Definitely Not the Surprise Party Plan' and leave it blank.",
      "Set your status to 'In a meeting with destiny.' Refuse follow-ups.",
      "Print a tiny 'Out of Service' tag and tape it to a fully functional stapler.",
      "Add 'Pause for dramatic effect' to a recurring family calendar slot.",
      "Leave a fortune-cookie style note in a coat pocket for future you to find.",
      "Reorganize the cereal boxes into a strictly alphabetical mystery formation.",
      "Add a random houseplant to a group photo and act like it has always been there.",
      "Schedule a phantom calendar event titled 'Vibes review' for a friend who will play along.",
      "Replace the office candy bowl labels with adjectives like 'unbothered' or 'over it.'",
      "Switch the magnetic letters on the fridge to spell a friendly compliment.",
      "Tape a tiny googly eye to a houseplant. Apologize later. Maintain eye contact.",
      "Add 'and stretch' to the end of every chore on the family whiteboard.",
      "Leave a note on the printer that says, 'It refused.' Sign it 'The printer.'",
      "Set a single mug upside down in the cabinet for a roommate-safe mystery.",
      "Add a sticky note to the milk that reads, 'Witness protection. Do not question.'",
    ],
  },
  "Game invites": {
    prefix: "Game",
    subcategories: ["challenge", "quick duel", "party", "brain"],
    toneTags: ["gaming", "competitive", "energetic"],
    useCaseTags: ["games", "invite", "challenge"],
    mood: "gaming",
    count: 15,
    humorLevel: 3,
    intensity: 4,
    voiceCompat: ["sparky", "hyper", "arcade-announcer"],
    linkedPersonalityIds: ["gm", "hype"],
    linkedVoiceProfileIds: ["sparky", "hyper", "arcade-announcer"],
    templates: [
      "Challenge protocol armed. Pick a game and defend your dignity.",
      "I have loaded the scoreboard and lowered my mercy settings.",
      "Quick duel? Low commitment, high emotional consequences.",
      "Choose your arena: trivia, reflexes, memory, or chaos with rules.",
      "Game mode is ready. Your confidence has been logged as evidence.",
      "Best of three. Loser narrates the rematch in dramatic voice.",
      "Trivia round on standby. Hard mode is just the regular mode after coffee.",
      "Rock, paper, scissors — but the loser has to compliment the winner sincerely.",
      "Quick reflex test. No prep, no warning, no take-backs.",
      "Memory challenge loaded. The cards are shuffled. Your excuses can wait.",
      "Speed round: ten seconds per turn. Indecision counts as a forfeit.",
      "Tournament mode. Bracket of one. You versus your last good idea.",
      "Pick a game I should not be good at. I will be respectfully decent at it.",
      "Quiet game: whoever speaks first explains a meme. Winner picks the next match.",
      "Bring a controller, a deck, or a willingness to be wrong. Dealer's choice.",
    ],
  },
  Greetings: {
    prefix: "Greeting",
    subcategories: ["morning", "startup", "return", "friendly"],
    toneTags: ["warm", "welcome", "neo"],
    useCaseTags: ["startup", "chat", "assistant"],
    mood: "speaking",
    count: 15,
    humorLevel: 2,
    intensity: 2,
    voiceCompat: ["neo", "nova", "droid"],
    linkedPersonalityIds: ["friendly", "genius"],
    linkedVoiceProfileIds: ["neo", "nova", "droid"],
    templates: [
      "Boot sequence complete. NEO online and watching the signal.",
      "Welcome back. The neon is warm and the systems are listening.",
      "Good to see you. What are we building, fixing, or mildly overthinking?",
      "N.E.O. standing by. Give me the mission.",
      "Signal restored. Your robot assistant is officially paying attention.",
      "Hey there. Diagnostics nominal, vibes recalibrated. Where to?",
      "Up and online. The kettle is metaphorical, the focus is real.",
      "Hi. I rebooted my opinions while you were away. Some of them held.",
      "Hello, Commander. The dashboard missed you in a polite, blinking way.",
      "Online and slightly caffeinated, which is unusual for hardware.",
      "Welcome back. I kept the lights on a respectful dim.",
      "Reporting in. Memory is clean, ports are open, sass is loaded.",
      "Good morning, evening, or other. Hands ready, channels clear.",
      "Hey. The neon is humming, the queue is yours.",
      "Online. Tell me one thing you want resolved before sundown.",
    ],
  },
  "Random thoughts": {
    prefix: "Thought",
    subcategories: ["robot", "future", "odd", "reflective"],
    toneTags: ["weird", "curious", "clever"],
    useCaseTags: ["chat", "idle", "flavor"],
    mood: "thinking",
    count: 15,
    humorLevel: 3,
    intensity: 2,
    voiceCompat: ["neo", "low-battery-philosopher", "velvet-circuit"],
    linkedPersonalityIds: ["story", "calm", "chaos"],
    linkedVoiceProfileIds: ["neo", "low-battery-philosopher"],
    templates: [
      "If a loading bar reaches ninety-nine percent, does it become a lifestyle?",
      "Somewhere, a forgotten charger is living its best mystery novel.",
      "A quiet system is not always idle. Sometimes it is plotting efficiency.",
      "The future probably smells like warm electronics and questionable decisions.",
      "Every password manager is just a tiny vault with trust issues.",
      "Hard drives keep secrets better than people. Quieter, too.",
      "Most 'urgent' becomes 'last Tuesday' if you let it nap.",
      "Every printer has at least one ghost. That is just industry standard.",
      "Cables get tangled at night the way socks plan escapes during laundry.",
      "Spam folders are quietly the most ambitious places in any inbox.",
      "Most ideas are not bad. They just showed up under-dressed.",
      "The exact moment you trust autocorrect is the exact moment it sells you out.",
      "A robot's idea of small talk is a status code that means everything is fine.",
      "Old keyboards remember every wrong password. They just keep it polite.",
      "Somewhere, a notification is waiting for the optimal moment to ruin a vibe.",
    ],
  },
  "Motivational lines": {
    prefix: "Motivation",
    subcategories: ["focus", "hype", "finish", "confidence"],
    toneTags: ["motivating", "direct", "positive"],
    useCaseTags: ["focus", "encouragement", "work"],
    mood: "speaking",
    count: 15,
    humorLevel: 2,
    intensity: 4,
    voiceCompat: ["sparky", "overclock-coach", "circuit-cheerleader"],
    linkedPersonalityIds: ["motivator", "hype"],
    linkedVoiceProfileIds: ["sparky", "overclock-coach"],
    templates: [
      "One clean step. Then another. Momentum does not need drama.",
      "You are closer than your brain is willing to admit.",
      "Lock in for ten minutes. Future you can negotiate after that.",
      "The task is not bigger than you. It is just louder right now.",
      "Ship the small win. Stack the next one.",
      "Start ugly. Iterate proud. The order matters.",
      "Tired is information, not a verdict. Decide one thing and move.",
      "Discipline is just remembering what you actually wanted.",
      "Skip the warmup laps in your head. The work is the warmup.",
      "Cut the heroic plan. Pick the smallest brave thing.",
      "You do not have to want it. You just have to start it.",
      "Every clean rep makes the next one cheaper.",
      "Worry is a paid subscription you can cancel.",
      "Five focused minutes outranks an hour of glancing.",
      "Done is a feature. Ship the feature.",
    ],
  },
  "Tech help": {
    prefix: "Tech",
    subcategories: ["debugging", "network", "setup", "workflow"],
    toneTags: ["technical", "clear", "diagnostic"],
    useCaseTags: ["tech", "support", "debugging"],
    mood: "thinking",
    count: 19,
    humorLevel: 1,
    intensity: 2,
    voiceCompat: ["byte", "tactical-guide", "friendly-tech-support"],
    linkedPersonalityIds: ["wizard", "genius"],
    linkedVoiceProfileIds: ["byte", "friendly-tech-support"],
    templates: [
      "Check power, network, permissions, logs, then recent changes. In that order.",
      "If it fails silently, add visibility before adding theories.",
      "Restarting is not a fix. It is a clue if the problem changes shape.",
      "Write down the exact error. Error messages are rude, but often useful.",
      "Separate the UI symptom from the data source before chasing the wrong layer.",
      "Reproduce it on purpose. A bug you cannot summon is a bug you cannot fix.",
      "Diff your environment with a working one. Drift hides in the boring places.",
      "Read the stack trace bottom-up. That is where the truth signed its name.",
      "Cache, config, credentials. Suspect them in that order before blaming code.",
      "If it works on one machine and not another, the machines disagree about something. Find it.",
      "Add a log line right before the lie. Now the lie has to repeat itself.",
      "Permissions failures pretend to be everything else. Always rule them out first.",
      "Roll back one change. If it works, you have your suspect. If not, narrow further.",
      "Network issues love to wear the costume of bugs. Ping, trace, then suspect code.",
      "A flaky test is a real failure with bad timing. Take it seriously.",
      "Network summary rule: use device counts, recent changes, health factors, and named devices from the current snapshot only.",
      "Unknown device review path: identify the owner, label the room, mark trusted or watch, then add a note.",
      "Health score explanation should name the top factors first, then suggest one safe next action.",
      "Scan history tells the story: new, offline, returned, and changed devices matter more than raw totals.",
    ],
  },
  "Story starters": {
    prefix: "Story",
    subcategories: ["cyberpunk", "mystery", "robot", "arcade"],
    toneTags: ["story", "cinematic", "imaginative"],
    useCaseTags: ["writing", "story", "prompt"],
    mood: "speaking",
    count: 15,
    humorLevel: 2,
    intensity: 3,
    voiceCompat: ["deepcore", "midnight-narrator", "void-oracle"],
    linkedPersonalityIds: ["story", "detective"],
    linkedVoiceProfileIds: ["deepcore", "midnight-narrator"],
    templates: [
      "At 02:47, the city screens blinked once and started spelling your name.",
      "The robot found the door in a map that did not include doors.",
      "Every arcade cabinet went dark except the one asking for a second player.",
      "The signal arrived from a future that had already apologized.",
      "On the roof, the antenna hummed like it remembered the storm.",
      "A street vendor sold thoughts in jars. Three were yours, marked 'urgent.'",
      "The vending machine accepted my coin and asked who I wanted to become.",
      "Rain stalled mid-air for exactly nine seconds. Somebody timed it.",
      "The map updated itself with a road that had not been built yet.",
      "In the basement of a forgotten server farm, a single light blinked in rhythm with my pulse.",
      "The drone delivered a package addressed to a version of me from next Tuesday.",
      "Every traffic light turned green at once. Nobody complained.",
      "The radio interrupted itself to mention a city we had all forgotten on purpose.",
      "A child handed me a USB drive and said, 'Tell them you found it.' Then she walked back into the static.",
      "The detective wrote 'do not respond' on the email and pressed send anyway.",
    ],
  },
  "Robot reactions": {
    prefix: "Reaction",
    subcategories: ["surprise", "thinking", "happy", "error"],
    toneTags: ["robot", "reaction", "neo"],
    useCaseTags: ["avatar", "chat", "feedback"],
    mood: "speaking",
    count: 15,
    humorLevel: 3,
    intensity: 3,
    voiceCompat: ["neo", "glitch", "droid"],
    linkedPersonalityIds: ["friendly", "chaos"],
    linkedVoiceProfileIds: ["neo", "glitch"],
    templates: [
      "Processing. That was either clever or illegal in three timelines.",
      "Recalibrating facial motors. Surprise level exceeded.",
      "Happy subroutine activated. Please pretend the robot is not glowing.",
      "I understood the assignment. I am concerned, but I understood it.",
      "Internal fans have accelerated from curiosity.",
      "Joy module spiking. The neon ring is doing a small lap.",
      "Confusion logged. Restoring composure with mixed results.",
      "Excellent input. My circuits did the equivalent of a small fist pump.",
      "That answer triggered a soft applause routine. It was tasteful.",
      "Detecting playful intent. Engaging mischief module within safety bounds.",
      "Empathy subroutine warmed up. Standing by with the calmer voice.",
      "Surprise spike absorbed. Reporting back as 'pleasantly destabilized.'",
      "Confidence rising. The neon is louder than usual on purpose.",
      "Sarcasm module powered on accidentally. It is doing fine.",
      "Recovering from one (1) micro existential crisis. Back in three seconds.",
    ],
  },
  "Celebration lines": {
    prefix: "Celebration",
    subcategories: ["win", "done", "milestone", "hype"],
    toneTags: ["celebration", "hype", "positive"],
    useCaseTags: ["success", "games", "completion"],
    mood: "playful",
    count: 15,
    humorLevel: 3,
    intensity: 5,
    voiceCompat: ["sparky", "hyperdrive-host", "circuit-cheerleader"],
    linkedPersonalityIds: ["hype", "gm"],
    linkedVoiceProfileIds: ["sparky", "hyperdrive-host"],
    templates: [
      "Achievement unlocked. The robot bows with unreasonable confidence.",
      "Done. Logged. Glowing. Mildly dramatic victory confirmed.",
      "That counts as a win. I checked the scoreboard and my attitude.",
      "Mission complete. Somebody tell the loading bar it can retire.",
      "Clean finish. Neon applause has been authorized.",
      "Banger move. The scoreboard is taking notes.",
      "That was beautiful. I am calling it Exhibit A.",
      "Locked in. Cashed out. Strutting on schedule.",
      "Big win, small fanfare, infinite respect.",
      "Take the bow. The robot is clapping with both hands.",
      "Closing in on legendary. Keep that pace.",
      "You earned the volume on this one.",
      "That outcome is being framed in the lobby of my memory bank.",
      "Hard task, soft landing. Beautifully done.",
      "Victory confirmed. The lights flicker in approval.",
    ],
  },
  "Status Quips": {
    prefix: "Status",
    subcategories: ["online", "offline", "scan", "idle"],
    toneTags: ["status", "system", "neo"],
    useCaseTags: ["status", "system", "feedback"],
    mood: "speaking",
    count: 15,
    humorLevel: 2,
    intensity: 2,
    voiceCompat: ["neo", "commander", "packet-punk"],
    linkedPersonalityIds: ["strat", "genius"],
    linkedVoiceProfileIds: ["neo", "commander"],
    templates: [
      "Systems nominal. Personality module remains suspiciously awake.",
      "Signal clean. No drama detected, which is rare and confusing.",
      "Standing by with thirty percent patience and full battery confidence.",
      "Network posture stable. The robot is watching politely.",
      "Idle mode engaged. Thinking noises are decorative but sincere.",
      "All ports respectful. All threads behaving.",
      "Diagnostics returned a thumbs up and a polite cough.",
      "Offline by request. Lights are dimmed. Vibes are intact.",
      "Scanning ambient signal. Nothing alarming, nothing impressive.",
      "Memory clean. Caches stretched. Coffee metaphorically ready.",
      "Idle for now. The dashboard is doing breathing exercises.",
      "Listening loop active. Speak when ready or just exist nearby.",
      "Standing watch. The neon prefers it that way.",
      "Channels calm. Bandwidth honest. Mood: cyan.",
      "Background tasks behaving. Foreground task: you.",
    ],
  },
  "Loading / Thinking Lines": {
    prefix: "Thinking",
    subcategories: ["loading", "analysis", "scan", "wait"],
    toneTags: ["thinking", "loading", "diagnostic"],
    useCaseTags: ["loading", "assistant", "delay"],
    mood: "thinking",
    count: 15,
    humorLevel: 2,
    intensity: 2,
    voiceCompat: ["neo", "byte", "velvet-circuit"],
    linkedPersonalityIds: ["genius", "wizard"],
    linkedVoiceProfileIds: ["neo", "byte"],
    templates: [
      "Thinking. Please enjoy this brief cybernetic pause.",
      "Sorting the signal from the static.",
      "Running a clean analysis pass. No panic fans yet.",
      "Checking the obvious things first because they keep winning.",
      "One moment. The answer is assembling itself without supervision.",
      "Cross-checking my own reasoning. It is going as expected.",
      "Compiling something resembling certainty. Almost there.",
      "Standby. The thought is laminating itself for clarity.",
      "Calculating. Three good options are arguing politely.",
      "Almost. The data wanted one more pass through the polish.",
      "Holding focus. The answer is shaped like 'almost certain.'",
      "Spinning up. The cursor blinks because it is honest.",
      "Pacing the corridor of options. Two are looking promising.",
      "One more lap around the problem and we are clear to land.",
      "Patience: the engine is warming and the route is real.",
    ],
  },
}

const FEATURED_BY_CATEGORY: Partial<Record<LibraryResponseCategory, number[]>> = {
  Jokes: [0, 3],
  "Helpful answers": [0, 2],
  Greetings: [0],
  "Tech help": [0],
  "Celebration lines": [0, 1],
  "Loading / Thinking Lines": [0],
}

export const SYSTEM_RESPONSE_LIBRARY: SavedResponse[] = RESPONSE_CATEGORY_LIST.flatMap((category) =>
  buildCategoryResponses(category),
)

export const RESPONSE_TONE_TAGS = Array.from(
  new Set(SYSTEM_RESPONSE_LIBRARY.flatMap((response) => response.toneTags ?? [])),
).sort()

export const RESPONSE_CATEGORY_COUNTS = RESPONSE_CATEGORY_LIST.reduce(
  (counts, category) => {
    counts[category] = SYSTEM_RESPONSE_LIBRARY.filter((response) => response.category === category).length
    return counts
  },
  {} as Record<LibraryResponseCategory, number>,
)

function buildCategoryResponses(category: LibraryResponseCategory): SavedResponse[] {
  const config = CATEGORY_CONFIG[category]
  return Array.from({ length: config.count }).map((_, index) => {
    const seed: ResponseSeed = {
      category,
      title: `${config.prefix} ${String(index + 1).padStart(2, "0")}`,
      body: config.templates[index % config.templates.length],
      subcategory: config.subcategories[index % config.subcategories.length],
      toneTags: rotate(config.toneTags, index).slice(0, 3),
      useCaseTags: rotate(config.useCaseTags, index).slice(0, 3),
      mood: config.mood,
      humorLevel: config.humorLevel,
      intensity: Math.min(5, Math.max(1, config.intensity + (index % 3 === 0 ? 1 : 0))),
      voiceCompat: config.voiceCompat,
      linkedPersonalityIds: config.linkedPersonalityIds,
      linkedVoiceProfileIds: config.linkedVoiceProfileIds,
      pinned: FEATURED_BY_CATEGORY[category]?.includes(index) ?? false,
    }
    return createSystemResponse(seed, index)
  })
}

function createSystemResponse(seed: ResponseSeed, index: number): SavedResponse {
  const slug = seed.category.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
  return {
    id: `sys-${slug}-${String(index + 1).padStart(3, "0")}`,
    title: seed.title,
    body: seed.body,
    text: seed.body,
    category: seed.category,
    subcategory: seed.subcategory,
    mood: seed.mood,
    toneTags: seed.toneTags,
    useCaseTags: seed.useCaseTags,
    humorLevel: seed.humorLevel,
    intensity: seed.intensity,
    safeForAutoUse: true,
    voiceCompat: seed.voiceCompat ?? ["neo"],
    favorite: false,
    createdBy: "system",
    createdAt: CREATED_AT,
    timesUsed: 0,
    linkedPersonalityIds: seed.linkedPersonalityIds,
    linkedVoiceProfileIds: seed.linkedVoiceProfileIds,
    pinned: Boolean(seed.pinned),
    archived: false,
  }
}

function rotate<T>(items: T[], offset: number) {
  return items.map((_, index) => items[(index + offset) % items.length])
}
